In [1]:
import numpy as np

In [2]:
x = np.load('/Users/jackradcliffe/PhD/eMERGE/average_weights/baseline_distribution.npy')

IOError: [Errno 2] No such file or directory: '/Users/jackradcliffe/PhD/eMERGE/average_weights/baseline_distribution.npy'

In [4]:
baseline = np.array([0,3])

def find_baseline_arg(baseline,baseline_distribution):
    j = 0 
    for i in baseline_distribution:
        if np.array_equal(i, baseline) == True:
            index = j
        j += 1
    try:
        return index
    except UnboundLocalError:
        print 'Baseline distribution doesn\'nt match, Quitting'
        exit()
        

find_baseline_arg(baseline,x)

2

In [5]:
x

array([[ 0,  1],
       [ 0,  2],
       [ 0,  3],
       [ 0,  5],
       [ 0,  6],
       [ 0,  8],
       [ 0,  9],
       [ 0, 10],
       [ 0, 11],
       [ 0, 12],
       [ 0, 13],
       [ 0, 14],
       [ 0, 15],
       [ 0, 16],
       [ 0, 17],
       [ 0, 18],
       [ 0, 19],
       [ 0, 20],
       [ 0, 21],
       [ 0, 23],
       [ 0, 24],
       [ 0, 25],
       [ 0, 26],
       [ 0, 27],
       [ 1,  2],
       [ 1,  3],
       [ 1,  5],
       [ 1,  6],
       [ 1,  8],
       [ 1,  9],
       [ 1, 10],
       [ 1, 11],
       [ 1, 12],
       [ 1, 13],
       [ 1, 14],
       [ 1, 15],
       [ 1, 16],
       [ 1, 17],
       [ 1, 18],
       [ 1, 19],
       [ 1, 20],
       [ 1, 21],
       [ 1, 23],
       [ 1, 24],
       [ 1, 25],
       [ 1, 26],
       [ 1, 27],
       [ 2,  3],
       [ 2,  5],
       [ 2,  6],
       [ 2,  8],
       [ 2,  9],
       [ 2, 10],
       [ 2, 11],
       [ 2, 12],
       [ 2, 13],
       [ 2, 14],
       [ 2, 15],
       [ 2, 16

In [9]:
x[:] = np.append(x[:],[0,0])

ValueError: could not broadcast input array from shape (602) into shape (300,2)

In [11]:
x.shape

(300, 2)

In [12]:
np.zeros(x.shape)

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,

In [15]:
np.append(x,np.zeros(x.shape),axis=1)

array([[  0.,   1.,   0.,   0.],
       [  0.,   2.,   0.,   0.],
       [  0.,   3.,   0.,   0.],
       ..., 
       [ 25.,  26.,   0.,   0.],
       [ 25.,  27.,   0.,   0.],
       [ 26.,  27.,   0.,   0.]])

In [33]:
weight = np.load('/Users/jackradcliffe/PhD/eMERGE/average_weights/weights.npy')

In [34]:
weight

array([[  0.        ,   1.        ,   0.32670616,   0.29979372,  56.        ],
       [  0.        ,   2.        ,   0.3120895 ,   0.2864081 ,  56.        ],
       [  0.        ,   3.        ,   0.21195186,   0.19167435,  56.        ],
       ..., 
       [ 25.        ,  26.        ,   0.31637827,   0.28810835,  56.        ],
       [ 25.        ,  27.        ,   0.27779119,   0.25105294,  56.        ],
       [ 26.        ,  27.        ,   0.27555463,   0.25159558,  56.        ]])

In [18]:
xtrue = [True,True]
xtrueF = [True,False]

In [24]:
data = [0.1,0]

In [25]:
np.delete(data,np.argwhere(xtrueF)==True)

/usr/local/lib/python2.7/site-packages/ipykernel_launcher.py:1: FutureWarning: in the future insert will treat boolean arrays and array-likes as boolean index instead of casting it to integer
  """Entry point for launching an IPython kernel.


array([ 0.])

In [35]:
weight = np.load('/Users/jackradcliffe/PhD/eMERGE/average_weights/weights.npy')
weight.T

array([[  0.        ,   0.        ,   0.        , ...,  25.        ,
         25.        ,  26.        ],
       [  1.        ,   2.        ,   3.        , ...,  26.        ,
         27.        ,  27.        ],
       [  0.32670616,   0.3120895 ,   0.21195186, ...,   0.31637827,
          0.27779119,   0.27555463],
       [  0.29979372,   0.2864081 ,   0.19167435, ...,   0.28810835,
          0.25105294,   0.25159558],
       [ 56.        ,  56.        ,  56.        , ...,  56.        ,
         56.        ,  56.        ]])

In [34]:
import numpy as np
def func2(x):
        out = [x[0]*x[1] - 3]
        out.append(x[1]*x[4] - 1)
        out.append(x[0]*x[4] - 1)
        return out
from scipy.optimize import fsolve
x02 = fsolve(func2, [1, 1,1])
print x02

IndexError: index 4 is out of bounds for axis 0 with size 4

In [157]:
import pandas as pd
df = pd.read_csv('/Users/jackradcliffe/PhD/eMERGE/average_weights/[JVLA1_small_data_av_wt.csv')
a = []
for i in df.ANTENNA1: ## take from antenna1
    if (i not in a) == True:
        a = a + [i]
for i in df.ANTENNA2: ## take from antenna2
    if (i not in a) == True:
        a = a + [i]

antenna1index = []
antenna2index = []
for i in range(len(df)):
    #print np.where(a==weight[i][0])[0][0]
    antenna1index = antenna1index + [np.where(a==df.ANTENNA1[i])[0][0]]
    antenna2index = antenna2index + [np.where(a==df.ANTENNA2[i])[0][0]]
    
antennaindex = pd.DataFrame({'ANT1_idx':np.array(antenna1index),'ANT2_idx':np.array(antenna2index)})

In [158]:
df = pd.concat([df, antennaindex],axis=1).to_csv('hi.csv')


In [163]:
## Set up simultaneous equations
def func(x):
    out = []
    df = pd.read_csv('hi.csv')
    for i in range(len(df)):
        out = out + [x[0]*x[1] - df['WEIGHT_average'][i]]
    return out

In [166]:
x02 = fsolve(func, np.zeros(16))

TypeError: fsolve: there is a mismatch between the input and output shape of the 'func' argument 'func'.Shape should be (16,) but it is (300,).

In [165]:
x02

array([ -6.58731086e-01,  -4.13069190e-01,  -2.08127117e-01,
        -3.16539412e+00,   8.54805987e+00,  -1.11683991e+01,
         1.62981623e+00,  -1.23416187e+01,   6.06174444e-02,
        -1.24654848e+01,  -8.60663149e-02,   5.99563502e+00,
         1.38172812e-01,   2.88702957e-01,   1.85061099e-01,
         2.17922450e-01,   2.60004812e-01,   3.03893405e-01,
         5.06019661e-01,   2.29159897e-01,   2.03163502e-01,
        -2.85284784e-01,   2.14058779e-01,   3.42230395e-01,
        -1.13274249e-02,   3.42371233e-01,   1.58878874e-01,
        -3.75062542e-02,  -4.28044636e-02,   1.49807983e-01,
        -1.62022129e-01,   3.72013660e-01,   1.68322575e-01,
         7.19370199e-02,   5.11019775e-02,   1.89447454e-01,
         2.40217565e-01,  -1.89616283e-02,   4.14243208e-01,
         2.00466302e-01,   2.19851470e-01,   1.66963303e-01,
         1.27389724e-01,   1.95260162e-01,   3.67501133e-01,
        -4.87327168e-02,  -1.90814448e-01,   3.97518702e-02,
         2.08469321e-01,

In [148]:
np.ones(len(a))

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [10]:
## Test 4 antennas with antenna weights
ant_weights = [1,20,40,50]

## Measured baseline weights are:
c01 = ant_weights[0]*ant_weights[1]
c02 = ant_weights[0]*ant_weights[2]
c03 = ant_weights[0]*ant_weights[3]
c13 = ant_weights[1]*ant_weights[3]
c12 = ant_weights[1]*ant_weights[2]
c23 = ant_weights[2]*ant_weights[3]

## Define functions where product of many variables = sum of baseline weights... 4 equations to solve!
def func_test(x):
    out = [x[0]*(x[1]+x[2]+x[3]) - c01 - c02 - c03] 
    out.append(x[1]*(x[0]+x[2]+x[3]) - c01 - c12 - c13)
    out.append(x[2]*(x[0]+x[1]+x[3]) - c02 - c12 - c23)
    out.append(x[3]*(x[0]+x[1]+x[2]) - c03 - c13 - c23)
    return out
from scipy.optimize import fsolve, lsq_linear
import numpy as np

## Put this into scipy solver
x0 = fsolve(func_test, np.ones(4))

In [11]:
x0

array([ 1.01829057, 20.0263333 , 39.99156169, 49.97035729])

In [7]:
print x0[0]*(x0[1]+x0[2]+x0[3])
print c01 + c02 + c03
print x0[1]*(x0[0]+x0[2]+x0[3]) 
print c01 + c12 + c13
print x0[2]*(x0[0]+x0[1]+x0[3])
print c02 + c12 + c23
print x0[3]*(x0[0]+x0[1]+x0[2])
print c03 +c13 + c23

8.99999999991371
9
16.000000000702407
16
21.00000000329278
21
24.00000000122646
24


In [4]:
print x0[0]*x0[1]
print x0[0]*x0[2]
print x0[0]*x0[3]
print x0[1]*x0[2]
print x0[1]*x0[3]
print x0[2]*x0[3]

1.999999999881655
3.000000000378429
3.9999999996536264
6.000000001081133
7.99999999973962
12.000000001833214


In [ ]:
## Set up range
